fix: wrap expr with parens when passing it to `implicit_try_match!`
Fixes struct expressions causing syntax errors:

    error: struct literals are not allowed here
       --> tests/test.rs:181:26
        |
    181 |     assert_eq!(match_ok!(A { x: 42 }, A { x }), Some(42));
        |                          ^^^^^^^^^^^
        |
    help: surround the struct literal with parentheses
        |
    181 |     assert_eq!(match_ok!((A { x: 42 }), A { x }), Some(42));
        |                          +           +